iterations: 200000

num_sky_gaussians: 100000

uncertainty_enabled: true
uncertainty_warmup_start: 35000
uncertainty_warmup_iters: 5000
uncertainty_mode: "dino"
use_boundary_penalty: true

appearance_enabled: true
appearance_n_fourier_freqs: 5
appearance_dropout: 0.2
